---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       Pointspace
keywords:    
description: "Official site for the Pointspace project"
source_link: "widve.github.io/Pointspace"
favicon:     "favicon/favicon.ico"
touch_icon:  "favicon/apple-icon.png"
google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  uw-red: '#c5050c'
  uw-red-dark:   '#9b0000'
  uw-page-bg:    '#f7f7f7'
  uw-gray-blue:  '#dadfe1'
  uw-gray-darker:   '#646569'
  uw-gray-darkest:   '#282728'
  uw-body-font:  '#494949'
  uw-anchor-color:   '#0479a8'
  uw-text: '#ffffff'
  uw-gray-footer-text:   '#adadad'
  uw-gray-footer-text-hover: '#f9f9f9'

kramdown:
  auto_ids:  false

